name:                my-xmonad
version:             0.1.0.0
github:              "githubuser/my-xmonad"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/my-xmonad#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates

library:
  source-dirs: src/lib
  exposed-modules:
    - Theme.Theme
    - Utils.XdgDesktopEntry
    - Utils.Run
    - Utils.Dunst
    - Hooks.AvoidDocksFloat
    - Xmobar.Plugins.SimpleIOReader
  dependencies:
    - xmonad
    - xmobar
    - xmonad-contrib
    - containers
    - text
    - filepattern
    - config-ini
    - process

executables:
  xmonad:
    source-dirs: src
    main: xmonad.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - xmonad
      - xmonad-contrib
      - containers
      - my-xmonad
  xmobar:
    source-dirs: src
    main: xmobar.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - xmobar
      - xmonad-contrib
      - containers
      - transformers
      - my-xmonad
  xmonadctl:
    source-dirs: src
    main: xmonadctl.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - X11
